# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'samrtble' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

pod 'SpreadsheetView'
pod 'SwiftyJSON'
pod 'MOLH'
pod 'SideMenu'
pod 'Firebase/Analytics'
pod 'Firebase/Messaging'
pod 'Firebase/Crashlytics', '~> 7.9.0'
 pod 'Alamofire', '~> 5.2'
end
